version: '3.7'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - app1_net
      - app2_net
      
  app1:
    image: https:latest
    networks:
      - app1_net

  app2:
    image: https:latest
    networks:
      - app2_net

networks:
  app1_net:
  app2_net:
